class PlayerCharacter():
	def __init__(self):
		self.buildCharacter()
		print("You have a character!")

	def buildCharacter(self):
		self.name = "TBD"
		self.pstr = 10
		self.strmod = 0
		self.dex = 10
		self.dexmod = 0 
		self.con = 10
		self.conmod = 0
		self.pint = 10
		self.intmod = 0
		self.wis = 10
		self.wismod = 0
		self.cha = 10
		self.chamod = 0
		self.classes = "Fighter 1"
		self.background = "Merchant"
		self.pname = "IDK"
		self.race = "Human"
		self.alignment = "CN"
		self.xp = 0
		self.ac = 10
		self.init = self.dexmod
		self.speed = 30
		self.hpmax = 10
		self.hpcurrent = 10
		self.hptemp = 0
		self.hptotal = 10
		self.hd = 1
		self.ptraits = "a" 
		self.ideals = "a"
		self.bonds = "a"
		self.flaws = "a"
		self.passivep = 0 #Passive Perception
		self.profs = "a"
		self.features = "a"
		self.equipment = "a"
		self.cp = 0
		self.sp = 0
		self.ep = 0
		self.gp = 0
		self.pp = 0
		self.attacks = 0
		self.wpn1 = 0
		self.wpn2 = 0
		self.wpn3 = 0
		self.wpn1atk = 0
		self.wpn2atk = 0
		self.wpn3atk = 0
		self.wpn1dmg = 0
		self.wpn2dmg = 0
		self.wpn3dmg = 0
		self.inspir = 0
		self.prof = 0
		self.ststr = 0
		self.stdex = 0
		self.stcon = 0
		self.stint = 0
		self.stwis = 0
		self.stcha = 0
		self.acro = 0
		self.animal = 0
		self.aracna = 0
		self.athletics = 0
		self.deception = 0
		self.history = 0
		self.insight = 0
		self.intimidation = 0
		self.investigation = 0
		self.medicine = 0
		self.nature = 0
		self.perception = 0
		self.performance = 0
		self.persuasion = 0
		self.religion = 0
		self.sleight = 0
		self.stealth = 0
		self.survival = 0